Develop feat : add features
sigmaclap/java-filmorate pull request #17
Opened 2023-04-29 10:33 UTC by sigmaclap

Добавлены все необходимые функциональности. 

1. Функциональность  «Отзывы»
2. Функциональность «Поиск»
3. Добавление режиссёров в фильмы
4. Функциональность «Общие фильмы»
5. Вывод самых популярных фильмов по жанру и годам
6. Удаление фильмов и пользователей
7. Функциональность «Рекомендации»
8. Функциональность «Лента событий»

2023-04-30 18:52 UTC, Fleaman777 requested changes

2023-04-30 18:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +            log.info("Пользователь с идентификатором {} не найден, лента событий не показана.", userId);
аналагично с лог левелом здесь и в др местах

2023-04-30 19:00 UTC, Fleaman777 requested changes

2023-04-30 19:00 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/constants/SQLScripts.java
>  }
ооочень грамотные запросы,
молодцы!

и составлены хорошо и выглядят отлично

2023-04-30 19:01 UTC, Fleaman777 reviewed
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
У вас очень круто все получилось. Есть, конечно, что поправить, но ничего глобального, в основном какие-то косметические моменты.
Очень понравились ваши запросы, составлены грамотно и оптимально, для самого начала карьеры - это достойный уровень. Сама логика в сервисах, тоже на отлично, так же как и контроллеры
Так держать 💪🏼

2023-05-01 08:20 UTC, sigmaclap commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (TITLE_PROPERTY.equals(options)) {
Создатели курса принципиально просили использовать 11 версию на протяжении всего обучения)

2023-05-02 08:15 UTC, Fleaman777 requested changes
Отличные исправления! Осталось пару незначительных моментов и можно будет принять работу

2023-05-02 08:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    public Director makeDir(ResultSet rs) throws SQLException {
нужно ли этому методу иметь публичный модификатор доступа?

2023-05-02 08:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Boolean isPositive;
такое название больше подходит методу, т.к. начинается с глагола, 
а для поля класса можно просто оставить positive

2023-05-02 08:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/constants/SQLScripts.java
> +            "GROUP BY ulf.USER_ID)";
этот запрос нужно немного оптимизировать с помощью JOIN 
т.к. по требованиям к работе, запрос не должен содержать 2 вложенных запроса

2023-05-02 08:15 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        List<Integer> genresId = film.getGenres().stream().map(Genre::getId).collect(Collectors.toList());
стрим чуть лучше воспринимается, когда он написан в стрим формате,
каждый метод стрима на своей строке

2023-05-04 09:42 UTC, Fleaman777 approved these changes
Все отлично.
Можно еще раз однозначно сказать, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении, да и в целом, в новой карьере

2023-05-07 14:35 UTC, merged